version: "3.4"
services:
    frontend:
        build: 
            context: ./frontend
            args:
                - API_URL=52.160.67.118
                #- API_URL=localhost
        #image: demo-front-app:latest
        container_name: demo-front
        hostname: demo-front
        ports:
            - "90:80"
        depends_on:
            - backend
    backend:
        environment:
            - ASPNETCORE_ENVIRONMENT=DockerAdmin
            #- ASPNETCORE_ENVIRONMENT=DockerWebApp
        build: ./backend
        #image: demo-back-app:latest
        container_name: demo-back
        hostname: demo-back
        ports:
            - "5000:80"
            - "44349:443"
        networks:
            - overlay
        extra_hosts:
            - "DEMOTEST:10.0.75.1"
        depends_on:
            - sql.data
    sql.data:
        image: crobles10/summit_dev:3.0
        container_name: sql.data
        hostname: sql.data
        ports:
            - "1433:1433"
        networks:
            - overlay

networks:
  overlay: